### ISSUE TITLE
Consider adding awto to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [awto-rs/awto#1]
Hey @tqwewe, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by tqwewe** [comment]
Hey @billy1624 👋 

Thanks for the suggestion! I am not sure if I'll make a PR for now as I haven't touched awto for a while and don't feel it's worthy enough haha but if I come back to it I may make a PR.

Though if you'd like to add it to the list manually that's fine with me :)

**Comment by billy1624** [comment]
Hey @tqwewe, I have added awto to the list. Checkout https://github.com/SeaQL/sea-orm/commit/55cf33755d25e837cd8869e5c476b2fee8d51371

**Comment by tqwewe** [comment]
Great thank you :)
